name: block_10_30

test_df: './input/testing_dataset.csv'
pssm_dir: 'pssm'
tert_dir: 'tert'
max_len: 250
batch_size: 1
input_shape: 1 84 250 250
n_dist_bins: 10
n_blocks: 10
checkpoint: './checkpoints/block_10_30.pt'
