name: train_config

train_df: './input/small_dataset.csv'
valid_df: './input/validation_dataset.csv'
pssm_dir: 'pssm'
tert_dir: 'tert'
max_len: 250
batch_size: 1
input_shape: 1 84 250 250
n_dist_bins: 10
n_blocks: 4
n_epochs: 4
lr: 0.001
